### ISSUE TITLE
Players can't join open rooms

### ISSUE THREAD

**Issue by Mike-Le-Pauvre** [evan3334/ChatRooms#4]
Hey!  Me again!

Well, title says everything there is to say, players can't join open rooms!  I don't know if there's a new permission for the open rooms or something but they don't seem to be a thing anymore!

Alright, Thanks!

**Comment by evan3334** [comment]
Are there any exceptions/errors in the console when they attempt to do this, or does it just quietly prevent  players from joining an open room?

**Comment by Mike-Le-Pauvre** [comment]
It tells them "You are not invited to the room (name)" even if it is open.  /cr list shows the name of the room in green.  I also get the message saying they tried to join a room they were not invited in.

**Comment by evan3334** [comment]
Ok, I'll take a look at the first opportunity I get. Sorry for my late first response, I've been quite busy lately :P

**Comment by Mike-Le-Pauvre** [comment]
It's fine don't worry, this is not a major issue anyway!
