### ISSUE TITLE
Can't find the plugin

### ISSUE THREAD

**Issue by navidmx** [evan3334/ChatRooms#7]
The site isn't up or something - just returns Error 404 and I'd really like to try the plugin.
Thanks!

**Comment by evan3334** [comment]
Oh yeah, I had to reinstall my web server and forgot to reupload the plugin. I'd advise that you use it with caution though - version 2 has a lot of bugs and performance issues that can cause problems.

**Comment by navidmx** [comment]
Is there a more stable version? In that case, can you upload that? I'm
running on 1.7.10.

**Comment by evan3334** [comment]
There isn't a more stable version. I started work on it a long time ago, but kind of lost interest and time for a while... I'm not sure when i'll start again. I'll upload the current version though.
