### ISSUE TITLE
Chat not showing up

### ISSUE THREAD

**Issue by DropTrooperColo** [evan3334/ChatRooms#8]
So i've been trying to get this to work in multiple ways but have not found any luck. So basically public chat works but once I switch to a room and try typing nothing pops up, not even a error in console or anything.

**Comment by evan3334** [comment]
I wrote this like two years ago and to tell you the truth I just now remembered it existed. It's a mess and I've decided to discontinue support on it. I may rewrite it someday but I'd honestly recommend using something else. Sorry for the inconvenience.
